[package]
authors = ["Hannu Hartikainen <hannu.hartikainen@gmail.com>"]
name = "pcd8544-hal"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0"
embedded-hal-bus = "0.3.0"
fpa = "0.1.0"
nb = "0.1.1"
