name: rust-clippy

on:
  push:

jobs:
  clippy:
    name: Run rust-clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: Install required cargo
        run: cargo install clippy

      - name: Run rust-clippy
        run:
          cargo clippy
          --all-features
          --message-format=json
        continue-on-error: true
